### ISSUE TITLE
Middleware redirect issue

### ISSUE THREAD

**Issue by spm32** [git-token/api-middleware#11]
Dashboard attempts to redirect to .org after accepting ToU.

> This gittoken.org page can’t be found
> 
> No webpage was found for the web address: https://gittoken.org/auth/github/callback?code=93a048cff3b34fd11d3c
>

**Comment by spm32** [comment]
New error after accepting ToU:

```
AuthorizationError: The redirect_uri MUST match the registered callback URL for this application.
    at Strategy.OAuth2Strategy.authenticate (/gittoken-server/node_modules/passport-oauth2/lib/strategy.js:131:25)
    at attempt (/gittoken-server/node_modules/passport/lib/middleware/authenticate.js:348:16)
    at authenticate (/gittoken-server/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at Layer.handle [as handle_request] (/gittoken-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/gittoken-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/gittoken-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/gittoken-server/node_modules/express/lib/router/layer.js:95:5)
    at /gittoken-server/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/gittoken-server/node_modules/express/lib/router/index.js:335:12)
    at next (/gittoken-server/node_modules/express/lib/router/index.js:275:10)
    at SessionStrategy.strategy.pass (/gittoken-server/node_modules/passport/lib/middleware/authenticate.js:325:9)
    at SessionStrategy.authenticate (/gittoken-server/node_modules/passport/lib/strategies/session.js:71:10)
    at attempt (/gittoken-server/node_modules/passport/lib/middleware/authenticate.js:348:16)
    at authenticate (/gittoken-server/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at Layer.handle [as handle_request] (/gittoken-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/gittoken-server/node_modules/express/lib/router/index.js:317:13)
    at /gittoken-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/gittoken-server/node_modules/express/lib/router/index.js:335:12)
    at next (/gittoken-server/node_modules/express/lib/router/index.js:275:10)
    at initialize (/gittoken-server/node_modules/passport/lib/middleware/initialize.js:53:5)
    at Layer.handle [as handle_request] (/gittoken-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/gittoken-server/node_modules/express/lib/router/index.js:317:13)
    at /gittoken-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/gittoken-server/node_modules/express/lib/router/index.js:335:12)
    at next (/gittoken-server/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/gittoken-server/node_modules/express-session/index.js:489:7)
    at runCallback (timers.js:676:20)
    at tryOnImmediate (timers.js:645:5)
```

**Comment by Ryanmtate** [comment]
Error was a mismatch between the deployed api callback URI; re-deploying

This is an environmental variable set for the `gittoken-server`

`GITHUB_API_CALLBACK_URL`
